import './styles.css';

type Char={name:string;type:string;stats:number[];faction:string};
type Room=any;
const chars:Char[]=[
{name:'王騎',type:'天下を見据える大将軍',stats:[97,93,100,99,94],faction:'秦・王騎軍'},
{name:'信',type:'本能で道を切り開く猛将',stats:[97,77,97,94,96],faction:'秦・飛信隊'},
{name:'蒙恬',type:'柔軟に勝ち筋を作る知将',stats:[87,95,91,96,92],faction:'秦・楽華隊'},
{name:'王賁',type:'誇り高き精鋭将',stats:[94,95,93,85,94],faction:'秦・玉鳳隊'},
{name:'李牧',type:'天下を盤上から動かす軍師',stats:[92,100,95,93,95],faction:'趙・三大天'},
{name:'桓騎',type:'常識を裏切る異端の将',stats:[91,99,89,100,94],faction:'秦・桓騎軍'},
{name:'蒙武',type:'力で戦場をねじ伏せる猛将',stats:[100,85,95,82,100],faction:'秦・蒙武軍'},
{name:'羌瘣',type:'静かに敵を討つ天才剣士',stats:[95,91,82,95,97],faction:'秦・飛信隊'},
{name:'楊端和',type:'異民族を束ねる女王',stats:[95,88,97,98,95],faction:'秦・山の民'},
{name:'王翦',type:'勝利を確信して動く戦略家',stats:[92,100,99,85,97],faction:'秦・王翦軍'},
{name:'廉頗',type:'経験で戦場を制する名将',stats:[97,92,98,96,100],faction:'魏・元三大天'}];
const labels=['武力','知略','統率','魅力','胆力'];
const q=[['仲間が敵に囲まれた。まず何をする？',['自分が先頭に立って突破','状況を分析して活路を探す','全員を鼓舞して隊列を整える','一度退いて立て直す']],['勝負で一番大事なのは？',['圧倒的な強さ','読み合いと情報','仲間との信頼','勝てるタイミング']],['リーダーになったら？',['前線に出る','作戦を考える','皆の力を引き出す','勝てる方法を選ぶ']],['裏切りが起きたら？',['問い詰める','理由を探る','仲間を守る','利用できるなら利用する']],['敵将と一騎打ちなら？',['喜んで受ける','癖を観察する','仲間のために戦う','勝てる条件を作る']],['相談されたら？',['熱く背中を押す','一緒に整理する','最後まで寄り添う','現実的に答える']],['大軍を率いるなら？',['勢いで押す','弱点を突く','士気を上げる','地形を利用する']],['自分の短所は？',['無茶しがち','考えすぎる','人を優先する','割り切りが早い']],['絶対に負けたくないのは？',['力の勝負','頭脳戦','仲間を守ること','結果を出すこと']],['尊敬できる敵がいたら？',['正面から認める','能力を分析','仲間になれないか考える','利用価値を考える']],['危機で頼るものは？',['自分の腕','判断力','仲間','冷静さ']],['どう見られたい？',['強い人','頭が切れる人','頼れる人','結果を出す人']],['作戦失敗なら？',['もう一度攻める','原因分析','皆を立て直す','別の勝ち筋へ']],['得意そうな戦場は？',['突破戦','奇襲・策','指揮・援護','心理戦']],['天下を取るなら？',['自分の力','知略','仲間と一緒','どんな手段でも']]] as const;
const app=document.querySelector<HTMLDivElement>('#app')!;
const playerId=localStorage.getItem('kingdom-player-id')||crypto.randomUUID(); localStorage.setItem('kingdom-player-id',playerId);
let playerName=localStorage.getItem('kingdom-player-name')||'しあん軍',scores=[0,0,0,0],current=0,character=chars[0];
let socket:WebSocket|null=null,poll:number|undefined,activeCode='';
const api={async post(path:string,body:any){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return {data:await r.json()};},async get(path:string){const r=await fetch(path);if(!r.ok)throw new Error(await r.text());return r.json();}};
function stopRoom(){if(poll)clearInterval(poll);poll=undefined;activeCode='';socket?.close();socket=null;}
function connectRoom(code:string,onUpdate:(r:Room)=>void){if(activeCode===code)return;stopRoom();activeCode=code;let last='';const pull=async()=>{try{const r=await api.get('/api/rooms/'+code);const sig=JSON.stringify(r);if(sig!==last){last=sig;onUpdate(r);}}catch{}};pull();poll=window.setInterval(pull,850);try{socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws?connection_id=${encodeURIComponent(playerId)}`);socket.onopen=()=>api.post('/api/rooms/subscribe',{code,connection_id:playerId}).catch(()=>{});socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='kingdom.room.update'&&m.payload?.room===code)onUpdate(m.payload.data);}catch{}};}catch{}}
function shell(body:string){return `<main><section class='panel'><header><span>KINGDOM</span><h1>天下統一録</h1><p>— 乱世を駆け、天下を取れ —</p></header>${body}<footer>FAN-MADE / 公式設定・公式診断ではありません</footer></section></main>`}
function btn(id:string,text:string,secondary=false){return `<button id='${id}' class='${secondary?'secondary':''}'>${text}</button>`}
function renderStart(){stopRoom();app.innerHTML=shell(`<div class='content center'><div class='seal'>将</div><h2>乱世を生き、天下を目指せ</h2><p>武将を見つけ、仲間を集め、戦場へ。</p>${btn('diag','武将を診断する')}${btn('group','🔥 三軍決戦')}${btn('online','🌐 オンライン対戦',true)}${btn('book','武将図鑑',true)}</div>`);document.querySelector('#diag')!.addEventListener('click',()=>{current=0;scores=[0,0,0,0];question();});document.querySelector('#group')!.addEventListener('click',groupHub);document.querySelector('#online')!.addEventListener('click',onlineLobby);document.querySelector('#book')!.addEventListener('click',book);}
function question(){const [text,answers]=q[current];app.innerHTML=shell(`<div class='content'><div class='progress'>第${current+1}問 / ${q.length}</div><h2 class='question'>${text}</h2><div class='answers'>${answers.map((a,i)=>`<button class='answer' data-i='${i}'>${a}</button>`).join('')}</div></div>`);document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>{scores[+(b as HTMLElement).dataset.i!]++;current++;current<q.length?question():showResult();}));}
function pickCharacter(){const profile=[[3,3,5,4],[7,1,3,4],[1,7,4,3],[4,4,3,4],[1,8,4,2],[3,3,2,7],[8,1,2,4],[5,4,1,5],[3,2,7,3],[1,6,5,3],[5,2,5,3]];return chars.map((c,i)=>({c,d:profile[i].reduce((s,t,j)=>s+(scores[j]-t)**2,0)})).sort((a,b)=>a.d-b.d)[0].c;}
function showResult(){character=pickCharacter();app.innerHTML=shell(`<div class='content result'><div class='badge'>あなたの武将</div><h2 class='big'>${character.name}</h2><h3>${character.type}</h3><p>${character.faction}</p><div class='power'>${Math.round(character.stats.reduce((a,b)=>a+b,0)/5)}<small>POWER</small></div><div class='stats'>${character.stats.map((v,i)=>`<div><span>${labels[i]}</span><i><b style='width:${v}%'></b></i><strong>${v}</strong></div>`).join('')}</div><p class='desc'>${character.type}。戦場では高い能力と個性を武器に天下を目指す。</p>${btn('unify','天下統一モード')}${btn('again','もう一度診断',true)}${btn('home','タイトルへ',true)}</div>`);document.querySelector('#unify')!.addEventListener('click',()=>unify(character));document.querySelector('#again')!.addEventListener('click',renderStart);document.querySelector('#home')!.addEventListener('click',renderStart);}
function book(){app.innerHTML=shell(`<div class='content'><h2>武将図鑑</h2><div class='grid'>${chars.map(c=>`<button class='card'><strong>${c.name}</strong><small>${c.type}</small></button>`).join('')}</div>${btn('back','戻る',true)}</div>`);document.querySelector('#back')!.addEventListener('click',renderStart);}
function onlineLobby(){app.innerHTML=shell(`<div class='content center'><div class='badge'>ONLINE</div><h2>友達と対戦</h2><label>名前<input id='name' value='${playerName}' maxlength='16'></label>${btn('make','通常対戦で部屋を作る')}${btn('makeGroup','🔥 三軍決戦で部屋を作る')}${btn('join','部屋に参加',true)}<div id='joinBox' class='hidden'><input id='code' maxlength='5' placeholder='部屋コード'><button id='joinNow'>参戦する</button></div>${btn('back','戻る',true)}</div>`);const saveName=()=>{playerName=(document.querySelector<HTMLInputElement>('#name')!.value||'しあん軍').trim();localStorage.setItem('kingdom-player-name',playerName);return playerName};document.querySelector('#make')!.addEventListener('click',()=>createRoom('battle',saveName()));document.querySelector('#makeGroup')!.addEventListener('click',()=>createRoom('group',saveName()));document.querySelector('#join')!.addEventListener('click',()=>document.querySelector('#joinBox')!.classList.toggle('hidden'));document.querySelector('#joinNow')!.addEventListener('click',async()=>{const name=saveName(),code=document.querySelector<HTMLInputElement>('#code')!.value.trim().toUpperCase();try{const r=await api.post('/api/rooms/join',{code,playerId,name,rank:'一般兵'});r.data.mode==='group'?groupOnlineRoulette(r.data):onlineMatch(r.data);}catch{alert('参加できないよ。コードを確認してね。')}});document.querySelector('#back')!.addEventListener('click',renderStart);}
async function createRoom(mode:'battle'|'group',name:string){try{const r=await api.post('/api/rooms',{playerId,name,rank:'一般兵',mode});waiting(r.data);}catch{alert('部屋を作れなかった。')}}
function waiting(room:Room){app.innerHTML=shell(`<div class='content center'><div class='badge'>ROOM</div><h2>友達を待っています</h2><div class='room'>${room.code}</div><p>このコードを友達に送ってね。</p>${btn('cancel','キャンセル',true)}</div>`);document.querySelector('#cancel')!.addEventListener('click',()=>{stopRoom();renderStart()});connectRoom(room.code,r=>{if(r.guest){if(r.mode==='group')groupOnlineRoulette(r);else onlineMatch(r);}})}
function onlineMatch(room:Room){const me=room.host.id===playerId?room.host:room.guest,foe=room.host.id===playerId?room.guest:room.host;app.innerHTML=shell(`<div class='content center'><div class='badge'>MATCH FOUND</div><h2>${me.name} VS ${foe.name}</h2><p>${foe.rank||'一般兵'}</p>${btn('startOnline','診断を開始')}${btn('exit','戻る',true)}</div>`);document.querySelector('#startOnline')!.addEventListener('click',()=>{current=0;scores=[0,0,0,0];onlineQuestion(room)});document.querySelector('#exit')!.addEventListener('click',renderStart);}
function onlineQuestion(room:Room){const [text,answers]=q[current];app.innerHTML=shell(`<div class='content'><div class='badge'>ROOM ${room.code}</div><div class='progress'>第${current+1}問 / ${q.length}</div><h2 class='question'>${text}</h2><div class='answers'>${answers.map((a,i)=>`<button class='answer' data-i='${i}'>${a}</button>`).join('')}</div></div>`);document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>{scores[+(b as HTMLElement).dataset.i!]++;current++;current<q.length?onlineQuestion(room):submitResult(room);}));}
async function submitResult(room:Room){const c=pickCharacter(),total=Math.round(c.stats.reduce((a,b)=>a+b,0)/5);try{const r=await api.post('/api/rooms/result',{code:room.code,playerId,character:c.name,stats:c.stats,total});r.data.hostResult&&r.data.guestResult?onlineReveal(r.data):onlineWait(r.data);}catch{alert('結果送信に失敗したよ。')}}
function onlineWait(room:Room){app.innerHTML=shell(`<div class='content center'><div class='badge'>RESULT</div><h2>相手の結果を待っています…</h2><div class='pulse'></div></div>`);connectRoom(room.code,r=>{if(r.hostResult&&r.guestResult)onlineReveal(r)})}
function onlineReveal(room:Room){const me=room.host.id===playerId?room.hostResult:room.guestResult,foe=room.host.id===playerId?room.guestResult:room.hostResult;app.innerHTML=shell(`<div class='content center'><div class='badge'>BATTLE READY</div><h2>${me.character} VS ${foe.character}</h2><p>${me.total} vs ${foe.total}</p>${btn('battle','開戦')}${btn('back','戻る',true)}</div>`);document.querySelector('#battle')!.addEventListener('click',()=>onlineBattle(room,me,foe));document.querySelector('#back')!.addEventListener('click',renderStart)}
function onlineBattle(room:Room,me:any,foe:any){const wins=labels.map((l,i)=>({l,a:me.stats[i],b:foe.stats[i]}));app.innerHTML=shell(`<div class='content'><div class='badge'>FINAL WAR</div><h2>${me.character} VS ${foe.character}</h2><div class='rounds'>${wins.map(x=>`<div><span>${x.l}</span><strong>${x.a} − ${x.b}</strong></div>`).join('')}</div>${btn('finish','決着を見る')}</div>`);document.querySelector('#finish')!.addEventListener('click',()=>{const a=wins.filter(x=>x.a>x.b).length,b=wins.filter(x=>x.b>x.a).length;app.innerHTML=shell(`<div class='content center'><div class='badge'>WAR RESULT</div><h2>${a===b?'引き分け！':a>b?'あなたの勝利！':'友達軍の勝利！'}</h2><div class='power'>${a} − ${b}</div>${btn('againOnline','もう一度')}${btn('home','タイトルへ',true)}</div>`);document.querySelector('#againOnline')!.addEventListener('click',()=>{current=0;scores=[0,0,0,0];onlineQuestion(room)});document.querySelector('#home')!.addEventListener('click',renderStart)})}
function groupHub(){app.innerHTML=shell(`<div class='content center'><div class='badge'>NEW MODE</div><h2>🔥 三軍決戦</h2><p>3人の武将を選び、先鋒・副将・大将を決めて勝ち残れ。</p>${btn('cpu','CPU戦を始める')}${btn('online','オンライン三軍決戦',true)}${btn('back','戻る',true)}</div>`);document.querySelector('#cpu')!.addEventListener('click',cpuGroup);document.querySelector('#online')!.addEventListener('click',onlineLobby);document.querySelector('#back')!.addEventListener('click',renderStart)}
function cpuGroup(){const team=shuffle(chars).slice(0,3),foe=shuffle(chars.filter(c=>!team.includes(c))).slice(0,3);const roles=['先鋒','副将','大将'];showGroupBattle(team.map((c,i)=>({...c,role:roles[i],attrition:0})),foe.map((c,i)=>({...c,role:roles[i],attrition:0})),0,0)}
function shuffle<T>(a:T[]){return [...a].sort(()=>Math.random()-.5)}
function showGroupBattle(a:any[],b:any[],ai:number,bi:number){if(ai>=3||bi>=3){app.innerHTML=shell(`<div class='content center'><div class='badge'>三軍決戦 / FINAL</div><h2>${ai>=3?'CPU軍の勝利！':'三軍、天下を制す！'}</h2>${btn('again','もう一度')}${btn('home','タイトルへ',true)}</div>`);document.querySelector('#again')!.addEventListener('click',cpuGroup);document.querySelector('#home')!.addEventListener('click',renderStart);return}const x=a[ai],y=b[bi];const av=x.stats.map((v:number,i:number)=>v+(x.role==='先鋒'&&i===0?3:x.role==='副将'&&i===1?3:x.role==='副将'&&i===2?2:x.role==='大将'&&i===2?3:x.role==='大将'&&i===4?2:0)-x.attrition);const bv=y.stats.map((v:number,i:number)=>v+(y.role==='先鋒'&&i===0?3:y.role==='副将'&&i===1?3:y.role==='副将'&&i===2?2:y.role==='大将'&&i===2?3:y.role==='大将'&&i===4?2:0)-y.attrition);const aw=av.reduce((n,v,i)=>n+(v>bv[i]?1:0),0),bw=bv.reduce((n,v,i)=>n+(v>av[i]?1:0),0);const win=aw===bw?'both':aw>bw?'a':'b';app.innerHTML=shell(`<div class='content center'><div class='badge'>三軍決戦 / ${ai+bi+1}戦目</div><div class='duel'><div><small>あなた軍 / ${x.role}</small><h2>${x.name}</h2></div><div class='vs'>VS</div><div><small>CPU軍 / ${y.role}</small><h2>${y.name}</h2></div></div><div class='rounds'>${labels.map((l,i)=>`<div><span>${l}</span><strong>${av[i]} − ${bv[i]}</strong></div>`).join('')}</div><div class='battle-result'><strong>${win==='both'?'両将討死！':win==='a'?x.name+'が勝ち残る！':y.name+'が勝ち残る！'}</strong><small>仇討ち：次の将は前戦の勝者を倒した相手に全能力+1</small></div>${btn('next','次の武将へ')}</div>`);document.querySelector('#next')!.addEventListener('click',()=>{if(win==='a'){x.attrition++;b[bi].revenge=true;showGroupBattle(a,b,ai,bi+1)}else if(win==='b'){y.attrition++;a[ai].revenge=true;showGroupBattle(a,b,ai+1,bi)}else showGroupBattle(a,b,ai+1,bi)})}
function groupOnlineRoulette(room:Room){const key=room.host.id===playerId?'host':'guest';if(room.group?.rosters?.[key])return groupPick(room);const names=shuffle(chars).slice(0,3).map(c=>c.name);app.innerHTML=shell(`<div class='content center'><div class='badge'>ONLINE / 三軍決戦</div><h2>ルーレット中…</h2><div class='roulette'>${names.join(' / ')}</div><small>自軍内は重複なし。相手軍との重複はOK。</small></div>`);setTimeout(async()=>{try{const r=await api.post('/api/rooms/group-roster',{code:room.code,playerId,roster:names});groupPick(r.data)}catch{alert('ルーレット結果の送信に失敗')}} ,900)}
function groupPick(room:Room){const g=room.group;if(g.phase==='confirm')return groupConfirm(room);if(g.phase==='battle')return groupOnlineBattle(room);const key=room.host.id===playerId?'host':'guest',my=g.rosters[key],turns=[room.host.id,room.guest.id,room.guest.id,room.host.id,room.host.id,room.guest.id],picker=turns[g.turn];if(picker!==playerId){app.innerHTML=shell(`<div class='content center'><div class='badge'>TURN PICK</div><h2>相手の選択中…</h2><div class='pulse'></div><p>第${g.turn+1}選択を待っています。</p></div>`);connectRoom(room.code,r=>groupPick(r));return}const role=g.turn<2?'先鋒':g.turn<4?'副将':'大将',roles=g.roles[key],available=my.filter((n:string)=>!roles[n]);app.innerHTML=shell(`<div class='content'><div class='badge'>三軍決戦 / ${role}</div><h2>あなたの${role}を選択</h2><div class='grid'>${available.map((n:string)=>`<button class='card pick' data-name='${n}'><strong>${n}</strong><small>${chars.find(c=>c.name===n)?.type}</small></button>`).join('')}</div><p class='progress'>選択 ${g.turn+1} / 6</p></div>`);document.querySelectorAll('.pick').forEach(b=>b.addEventListener('click',async()=>{try{const r=await api.post('/api/rooms/group-pick',{code:room.code,playerId,character:(b as HTMLElement).dataset.name,role});groupPick(r.data)}catch{alert('今はあなたのターンじゃないか、選べない武将です。')}}));}
function groupConfirm(room:Room){const g=room.group,key=room.host.id===playerId?'host':'guest',other=key==='host'?'guest':'host';app.innerHTML=shell(`<div class='content'><div class='badge'>三軍決戦 / CONFIRM</div><h2>役職を確認</h2><div class='teams'><div><h3>あなた軍</h3>${['先鋒','副将','大将'].map(r=>`<p>${r}：${Object.entries(g.roles[key]).find(([,v])=>v===r)?.[0]||'—'}</p>`).join('')}</div><div><h3>相手軍</h3>${['先鋒','副将','大将'].map(r=>`<p>${r}：${Object.entries(g.roles[other]).find(([,v])=>v===r)?.[0]||'—'}</p>`).join('')}</div></div>${btn('confirm','この編成で決定')}${btn('back','戻る',true)}</div>`);document.querySelector('#confirm')!.addEventListener('click',async()=>{try{const r=await api.post('/api/rooms/group-confirm',{code:room.code,playerId});groupConfirm(r.data)}catch{alert('決定に失敗')}});document.querySelector('#back')!.addEventListener('click',onlineLobby);if(g.phase==='battle')groupOnlineBattle(room)}
function groupOnlineBattle(room:Room){const g=room.group;const a=Object.entries(g.roles.host).map(([n,r])=>({...chars.find(c=>c.name===n)!,role:r,attrition:0})).sort((x:any,y:any)=>['先鋒','副将','大将'].indexOf(x.role)-['先鋒','副将','大将'].indexOf(y.role));const b=Object.entries(g.roles.guest).map(([n,r])=>({...chars.find(c=>c.name===n)!,role:r,attrition:0})).sort((x:any,y:any)=>['先鋒','副将','大将'].indexOf(x.role)-['先鋒','副将','大将'].indexOf(y.role));showGroupBattle(a,b,0,0)}
function unify(c:Char){app.innerHTML=shell(`<div class='content center'><div class='badge'>天下統一</div><h2>${c.name}軍</h2><p>七雄を踏み越え、中華を統べよ。</p><div class='grid'>${chars.filter(x=>x.name!==c.name).map(x=>`<button class='card enemy' data-name='${x.name}'><strong>${x.name}</strong><small>${x.type}</small></button>`).join('')}</div>${btn('back','結果画面へ',true)}</div>`);document.querySelectorAll('.enemy').forEach(b=>b.addEventListener('click',()=>{const foe=chars.find(x=>x.name===(b as HTMLElement).dataset.name)!;const a=c.stats.reduce((s,v)=>s+v,0),bb=foe.stats.reduce((s,v)=>s+v,0);app.innerHTML=shell(`<div class='content center'><div class='badge'>天下決戦</div><h2>${c.name} VS ${foe.name}</h2><div class='power'>${a} − ${bb}</div><p>${a===bb?'互角の決着':a>bb?c.name+'軍の勝利！':foe.name+'軍の勝利！'}</p>${btn('back','戻る',true)}</div>`);document.querySelector('#back')!.addEventListener('click',()=>unify(c))}));document.querySelector('#back')!.addEventListener('click',showResult)}
renderStart();
